# Generated by Django 5.2 on 2025-07-16 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'FileUpload',
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rows', models.IntegerField()),
                ('total_columns', models.IntegerField()),
                ('missing_values_summary', models.JSONField()),
                ('data_types_detected', models.JSONField()),
                ('categorical_columns', models.JSONField()),
                ('numeric_columns', models.JSONField()),
                ('outliers_detected', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cleaner.fileupload')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cleaning_options', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('cleaned_file_path', models.CharField(blank=True, max_length=500)),
                ('numeric_file_path', models.CharField(blank=True, max_length=500)),
                ('cleaning_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaner.dataanalysis')),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaner.fileupload')),
            ],
        ),
    ]
